require("options")
require("colorscheme")
require("keybindings")
require("plugins")
-- require("plugin-config.neosolarized")
require("plugin-config.onedarkpro")
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.nvim-treesitter")
require("plugin-config.ident-blankline")
require("plugin-config.colorizer")
require("plugin-config.markdown-preview")
require("plugin-config.comment")
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
