require("options")
require("colorscheme")
require("keybindings")
require("plugins")
-- require("plugin-config.neosolarized")
require("plugin-config.nvim-tree")
require("plugin-config.bufferline")
require("plugin-config.lualine")
require("plugin-config.nvim-treesitter")
require("plugin-config.ident-blankline")
require("lsp.setup")
require("lsp.cmp")
require("lsp.ui")
